create table if not exists public.app_annonce_refresh_queue (
    id bigint generated by default as identity primary key,
    app_dossier_id bigint not null,
    hektor_annonce_id text,
    reason text not null,
    source text not null default 'online_action',
    requested_by text,
    status text not null default 'pending',
    attempt_count integer not null default 0,
    requested_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz,
    last_error text,
    payload_json jsonb not null default '{}'::jsonb,
    result_json jsonb not null default '{}'::jsonb
);

create index if not exists idx_app_annonce_refresh_queue_status
on public.app_annonce_refresh_queue (status, requested_at asc, id asc);

alter table public.app_annonce_refresh_queue enable row level security;

drop policy if exists "app_annonce_refresh_queue_select_admin" on public.app_annonce_refresh_queue;
create policy "app_annonce_refresh_queue_select_admin"
on public.app_annonce_refresh_queue
for select
using (public.is_app_manager_or_admin());
