create table if not exists public.app_dossier_current (
    app_dossier_id bigint primary key,
    hektor_annonce_id bigint not null,
    archive text,
    diffusable text,
    nb_portails_actifs integer,
    has_diffusion_error boolean,
    portails_resume text,
    offre_id text,
    offre_state text,
    offre_last_proposition_type text,
    compromis_id text,
    compromis_state text,
    vente_id text,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    ville text,
    type_bien text,
    prix numeric,
    commercial_id text,
    commercial_nom text,
    agence_nom text,
    statut_annonce text,
    validation_diffusion_state text,
    etat_visibilite text,
    alerte_principale text,
    priority text,
    has_open_blocker boolean not null default false,
    commentaire_resume text,
    date_relance_prevue date,
    dernier_event_type text,
    dernier_work_status text,
    source_updated_at text,
    source_hash text not null,
    refreshed_at timestamptz not null default now()
);

alter table public.app_dossier_current
add column if not exists offre_state text;

alter table public.app_dossier_current
add column if not exists compromis_state text;

alter table public.app_dossier_current
add column if not exists offre_last_proposition_type text;

create table if not exists public.app_dossier_detail_current (
    app_dossier_id bigint primary key,
    hektor_annonce_id bigint not null,
    source_updated_at text,
    source_hash text not null,
    detail_payload_json text not null,
    refreshed_at timestamptz not null default now()
);

create table if not exists public.app_work_item_current (
    id bigint generated by default as identity primary key,
    app_dossier_id bigint not null,
    hektor_annonce_id bigint not null,
    archive text,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    commercial_nom text,
    type_demande_label text,
    work_status text,
    internal_status text,
    priority text,
    validation_diffusion_state text,
    etat_visibilite text,
    motif_blocage text,
    has_open_blocker boolean not null default false,
    next_action text,
    date_relance_prevue date,
    date_entree_file timestamptz,
    date_derniere_action timestamptz,
    age_jours integer,
    source_hash text not null,
    refreshed_at timestamptz not null default now(),
    unique (app_dossier_id, type_demande_label, date_entree_file)
);

create table if not exists public.app_filter_catalog_current_store (
    id bigint generated by default as identity primary key,
    filter_type text not null,
    filter_value text not null,
    sort_order integer not null default 0,
    source_hash text not null,
    refreshed_at timestamptz not null default now(),
    unique (filter_type, filter_value)
);

create table if not exists public.app_delta_run (
    id uuid primary key default gen_random_uuid(),
    mode text not null default 'upgrade',
    status text not null default 'running',
    scope text not null default 'annonces_current',
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    dossiers_detected integer not null default 0,
    dossiers_upserted integer not null default 0,
    details_upserted integer not null default 0,
    work_items_replaced integer not null default 0,
    filters_replaced integer not null default 0,
    deleted_dossiers integer not null default 0,
    notes jsonb not null default '{}'::jsonb
);

create index if not exists idx_app_dossier_current_annonce on public.app_dossier_current (hektor_annonce_id);
create index if not exists idx_app_dossier_current_statut on public.app_dossier_current (statut_annonce, archive, diffusable);
create index if not exists idx_app_dossier_current_commercial on public.app_dossier_current (commercial_id, commercial_nom);
create index if not exists idx_app_dossier_detail_current_annonce on public.app_dossier_detail_current (hektor_annonce_id);
create index if not exists idx_app_work_item_current_status on public.app_work_item_current (work_status, internal_status, priority);
create index if not exists idx_app_work_item_current_annonce on public.app_work_item_current (hektor_annonce_id);
create index if not exists idx_app_filter_catalog_current_type on public.app_filter_catalog_current_store (filter_type, sort_order, filter_value);
create index if not exists idx_app_delta_run_started_at on public.app_delta_run (started_at desc, status);

create or replace view public.app_dashboard_v1
with (security_invoker=on) as
select
    null::uuid as sync_run_id,
    (select count(*) from public.app_dossiers_current) as total_dossiers,
    (select count(*) from public.app_work_items_current) as total_demandes,
    (select count(*) from public.app_dossiers_current where coalesce(numero_mandat, '') = '') as total_sans_mandat,
    (select count(*) from public.app_dossiers_current where coalesce(has_open_blocker, false) = true) as total_bloques,
    (select count(*) from public.app_dossiers_current where coalesce(validation_diffusion_state, '') = 'valide') as total_valides_diffusion,
    (select count(*) from public.app_dossiers_current where coalesce(etat_visibilite, '') = 'visible') as total_visibles;

create or replace view public.app_dossiers_current
with (security_invoker=on) as
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.archive,
    d.diffusable,
    d.nb_portails_actifs,
    d.has_diffusion_error,
    d.portails_resume,
    d.offre_id,
    d.offre_state,
    d.compromis_id,
    d.compromis_state,
    d.vente_id,
    d.numero_dossier,
    d.numero_mandat,
    d.titre_bien,
    d.ville,
    d.type_bien,
    d.prix,
    d.commercial_id,
    d.commercial_nom,
    d.negociateur_email,
    d.agence_nom,
    d.statut_annonce,
    d.validation_diffusion_state,
    d.etat_visibilite,
    d.alerte_principale,
    d.priority,
    d.has_open_blocker,
    d.commentaire_resume,
    d.date_relance_prevue,
    d.dernier_event_type,
    d.dernier_work_status,
    d.offre_last_proposition_type
from public.app_dossier_current d
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.archive,
    d.diffusable,
    d.nb_portails_actifs,
    d.has_diffusion_error,
    d.portails_resume,
    d.offre_id,
    d.offre_state,
    d.compromis_id,
    d.compromis_state,
    d.vente_id,
    d.numero_dossier,
    d.numero_mandat,
    d.titre_bien,
    d.ville,
    d.type_bien,
    d.prix,
    d.commercial_id,
    d.commercial_nom,
    d.negociateur_email,
    d.agence_nom,
    d.statut_annonce,
    d.validation_diffusion_state,
    d.etat_visibilite,
    d.alerte_principale,
    d.priority,
    d.has_open_blocker,
    d.commentaire_resume,
    d.date_relance_prevue,
    d.dernier_event_type,
    d.dernier_work_status,
    d.offre_last_proposition_type
from public.app_dossier_v1 d
join public.app_latest_sync_run r on r.id = d.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

create or replace view public.app_dossier_details_current
with (security_invoker=on) as
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.detail_payload_json
from public.app_dossier_detail_current d
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.detail_payload_json
from public.app_dossier_detail_v1 d
join public.app_latest_sync_run r on r.id = d.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

create or replace view public.app_work_items_current
with (security_invoker=on) as
select
    w.app_dossier_id,
    w.hektor_annonce_id,
    w.archive,
    w.numero_dossier,
    w.numero_mandat,
    w.titre_bien,
    w.commercial_nom,
    w.type_demande_label,
    w.work_status,
    w.internal_status,
    w.priority,
    w.validation_diffusion_state,
    w.etat_visibilite,
    w.motif_blocage,
    w.has_open_blocker,
    w.next_action,
    w.date_relance_prevue,
    w.date_entree_file,
    w.date_derniere_action,
    w.age_jours
from public.app_work_item_current w
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    w.app_dossier_id,
    w.hektor_annonce_id,
    w.archive,
    w.numero_dossier,
    w.numero_mandat,
    w.titre_bien,
    w.commercial_nom,
    w.type_demande_label,
    w.work_status,
    w.internal_status,
    w.priority,
    w.validation_diffusion_state,
    w.etat_visibilite,
    w.motif_blocage,
    w.has_open_blocker,
    w.next_action,
    w.date_relance_prevue,
    w.date_entree_file,
    w.date_derniere_action,
    w.age_jours
from public.app_work_item_v1 w
join public.app_latest_sync_run r on r.id = w.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

create or replace view public.app_filter_catalog_current
with (security_invoker=on) as
select
    c.filter_type,
    c.filter_value,
    c.sort_order
from public.app_filter_catalog_current_store c
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    c.filter_type,
    c.filter_value,
    c.sort_order
from public.app_filter_catalog_v1 c
join public.app_latest_sync_run r on r.id = c.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

alter table public.app_dossier_current enable row level security;
alter table public.app_dossier_detail_current enable row level security;
alter table public.app_work_item_current enable row level security;
alter table public.app_filter_catalog_current_store enable row level security;
alter table public.app_delta_run enable row level security;

drop policy if exists "app_dossier_current_select_active_users" on public.app_dossier_current;
create policy "app_dossier_current_select_active_users"
on public.app_dossier_current
for select
using (public.is_app_user_active());

drop policy if exists "app_dossier_detail_current_select_active_users" on public.app_dossier_detail_current;
create policy "app_dossier_detail_current_select_active_users"
on public.app_dossier_detail_current
for select
using (public.is_app_user_active());

drop policy if exists "app_work_item_current_select_active_users" on public.app_work_item_current;
create policy "app_work_item_current_select_active_users"
on public.app_work_item_current
for select
using (public.is_app_user_active());

drop policy if exists "app_filter_catalog_current_store_select_active_users" on public.app_filter_catalog_current_store;
create policy "app_filter_catalog_current_store_select_active_users"
on public.app_filter_catalog_current_store
for select
using (public.is_app_user_active());

drop policy if exists "app_delta_run_select_admin" on public.app_delta_run;
create policy "app_delta_run_select_admin"
on public.app_delta_run
for select
using (public.is_app_manager_or_admin());
