create or replace view public.app_annonces_current
with (security_invoker=on) as
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.archive,
    d.diffusable,
    d.adresse_privee_listing,
    d.adresse_detail,
    d.code_postal,
    d.code_postal_prive_detail,
    d.ville_privee_detail,
    d.nb_portails_actifs,
    d.has_diffusion_error,
    d.portails_resume,
    d.offre_id,
    d.offre_state,
    d.compromis_id,
    d.compromis_state,
    d.vente_id,
    d.numero_dossier,
    d.numero_mandat,
    d.titre_bien,
    d.ville,
    d.type_bien,
    d.prix,
    d.commercial_id,
    d.commercial_nom,
    d.negociateur_email,
    d.agence_nom,
    d.statut_annonce,
    d.photo_url_listing,
    d.images_preview_json,
    d.validation_diffusion_state,
    d.mandat_type,
    d.mandat_type_source,
    d.mandat_date_debut,
    d.mandat_date_fin,
    d.mandat_montant,
    d.mandants_texte,
    d.price_change_event_count,
    d.price_change_last_source_kind,
    d.price_change_last_old_value,
    d.price_change_last_new_value,
    d.price_change_last_detected_at,
    d.price_change_last_source_updated_at,
    d.etat_visibilite,
    d.alerte_principale,
    d.priority,
    d.has_open_blocker,
    d.commentaire_resume,
    d.date_relance_prevue,
    d.dernier_event_type,
    d.dernier_work_status,
    d.offre_last_proposition_type
from public.app_dossiers_current d
union all
select
    a.app_archive_id as app_dossier_id,
    a.hektor_annonce_id,
    coalesce(a.archive, '1') as archive,
    a.diffusable,
    null::text as adresse_privee_listing,
    null::text as adresse_detail,
    a.code_postal,
    null::text as code_postal_prive_detail,
    null::text as ville_privee_detail,
    0::integer as nb_portails_actifs,
    false as has_diffusion_error,
    null::text as portails_resume,
    null::text as offre_id,
    null::text as offre_state,
    null::text as compromis_id,
    null::text as compromis_state,
    null::text as vente_id,
    a.numero_dossier,
    a.numero_mandat,
    a.titre_bien,
    a.ville,
    a.type_bien,
    a.prix,
    a.commercial_id,
    a.commercial_nom,
    a.negociateur_email,
    a.agence_nom,
    a.statut_annonce,
    null::text as photo_url_listing,
    null::text as images_preview_json,
    null::text as validation_diffusion_state,
    a.mandat_type,
    null::text as mandat_type_source,
    a.mandat_date_debut,
    a.mandat_date_fin,
    a.mandat_montant,
    a.mandants_texte,
    0::integer as price_change_event_count,
    null::text as price_change_last_source_kind,
    null::numeric as price_change_last_old_value,
    null::numeric as price_change_last_new_value,
    null::text as price_change_last_detected_at,
    null::text as price_change_last_source_updated_at,
    null::text as etat_visibilite,
    null::text as alerte_principale,
    'normal'::text as priority,
    false as has_open_blocker,
    null::text as commentaire_resume,
    null::date as date_relance_prevue,
    null::text as dernier_event_type,
    null::text as dernier_work_status,
    null::text as offre_last_proposition_type
from public.app_archive_annonce_index_current a
where not exists (
    select 1
    from public.app_dossiers_current d
    where d.hektor_annonce_id = a.hektor_annonce_id
);
