create extension if not exists pgcrypto;

create type public.app_role as enum ('admin', 'manager', 'commercial', 'lecture');

create table if not exists public.app_user_profile (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique,
    role public.app_role not null default 'lecture',
    display_name text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.app_sync_run (
    id uuid primary key default gen_random_uuid(),
    source_name text not null default 'phase2.sqlite',
    contract_name text not null,
    status text not null default 'completed',
    generated_at timestamptz not null default now(),
    payload_meta jsonb not null default '{}'::jsonb,
    summary jsonb not null default '{}'::jsonb
);

create table if not exists public.app_summary_snapshot (
    sync_run_id uuid primary key references public.app_sync_run(id) on delete cascade,
    total_dossiers integer not null default 0,
    total_demandes integer not null default 0,
    total_sans_mandat integer not null default 0,
    total_bloques integer not null default 0,
    total_valides_diffusion integer not null default 0,
    total_visibles integer not null default 0
);

create table if not exists public.app_dossier_v1 (
    id bigint generated by default as identity primary key,
    sync_run_id uuid not null references public.app_sync_run(id) on delete cascade,
    app_dossier_id bigint not null,
    hektor_annonce_id bigint not null,
    archive text,
    diffusable text,
    adresse_privee_listing text,
    adresse_detail text,
    code_postal text,
    code_postal_prive_detail text,
    ville_privee_detail text,
    nb_portails_actifs integer,
    has_diffusion_error boolean,
    portails_resume text,
    offre_id text,
    offre_state text,
    offre_last_proposition_type text,
    compromis_id text,
    compromis_state text,
    vente_id text,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    ville text,
    type_bien text,
    prix numeric,
    commercial_id text,
    commercial_nom text,
    negociateur_email text,
    agence_nom text,
    statut_annonce text,
    photo_url_listing text,
    images_preview_json text,
    validation_diffusion_state text,
    mandat_type text,
    mandat_type_source text,
    mandat_date_debut text,
    mandat_date_fin text,
    mandat_montant numeric,
    mandants_texte text,
    etat_visibilite text,
    alerte_principale text,
    priority text,
    has_open_blocker boolean not null default false,
    commentaire_resume text,
    date_relance_prevue date,
    dernier_event_type text,
    dernier_work_status text,
    created_at timestamptz not null default now(),
    unique (sync_run_id, app_dossier_id)
);

create table if not exists public.app_dossier_detail_v1 (
    id bigint generated by default as identity primary key,
    sync_run_id uuid not null references public.app_sync_run(id) on delete cascade,
    app_dossier_id bigint not null,
    hektor_annonce_id bigint not null,
    detail_payload_json text not null,
    created_at timestamptz not null default now(),
    unique (sync_run_id, app_dossier_id)
);

create table if not exists public.app_work_item_v1 (
    id bigint generated by default as identity primary key,
    sync_run_id uuid not null references public.app_sync_run(id) on delete cascade,
    app_dossier_id bigint not null,
    hektor_annonce_id bigint not null,
    archive text,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    commercial_nom text,
    type_demande_label text,
    work_status text,
    internal_status text,
    priority text,
    validation_diffusion_state text,
    etat_visibilite text,
    motif_blocage text,
    has_open_blocker boolean not null default false,
    next_action text,
    date_relance_prevue date,
    date_entree_file timestamptz,
    date_derniere_action timestamptz,
    age_jours integer,
    created_at timestamptz not null default now(),
    unique (sync_run_id, app_dossier_id, type_demande_label, date_entree_file)
);

create table if not exists public.app_filter_catalog_v1 (
    id bigint generated by default as identity primary key,
    sync_run_id uuid not null references public.app_sync_run(id) on delete cascade,
    filter_type text not null,
    filter_value text not null,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    unique (sync_run_id, filter_type, filter_value)
);

create table if not exists public.app_dossier_current (
    app_dossier_id bigint primary key,
    hektor_annonce_id bigint not null,
    archive text,
    diffusable text,
    adresse_privee_listing text,
    adresse_detail text,
    code_postal text,
    code_postal_prive_detail text,
    ville_privee_detail text,
    nb_portails_actifs integer,
    has_diffusion_error boolean,
    portails_resume text,
    offre_id text,
    offre_state text,
    offre_last_proposition_type text,
    compromis_id text,
    compromis_state text,
    vente_id text,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    ville text,
    type_bien text,
    prix numeric,
    commercial_id text,
    commercial_nom text,
    negociateur_email text,
    agence_nom text,
    statut_annonce text,
    validation_diffusion_state text,
    mandat_type text,
    mandat_type_source text,
    mandat_date_debut text,
    mandat_date_fin text,
    mandat_montant numeric,
    mandants_texte text,
    etat_visibilite text,
    alerte_principale text,
    priority text,
    has_open_blocker boolean not null default false,
    commentaire_resume text,
    date_relance_prevue date,
    dernier_event_type text,
    dernier_work_status text,
    source_updated_at text,
    source_hash text not null,
    refreshed_at timestamptz not null default now()
);

create table if not exists public.app_dossier_detail_current (
    app_dossier_id bigint primary key,
    hektor_annonce_id bigint not null,
    source_updated_at text,
    source_hash text not null,
    detail_payload_json text not null,
    refreshed_at timestamptz not null default now()
);

create table if not exists public.app_work_item_current (
    id bigint generated by default as identity primary key,
    app_dossier_id bigint not null,
    hektor_annonce_id bigint not null,
    archive text,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    commercial_nom text,
    type_demande_label text,
    work_status text,
    internal_status text,
    priority text,
    validation_diffusion_state text,
    etat_visibilite text,
    motif_blocage text,
    has_open_blocker boolean not null default false,
    next_action text,
    date_relance_prevue date,
    date_entree_file timestamptz,
    date_derniere_action timestamptz,
    age_jours integer,
    source_hash text not null,
    refreshed_at timestamptz not null default now(),
    unique (app_dossier_id, type_demande_label, date_entree_file)
);

create table if not exists public.app_filter_catalog_current_store (
    id bigint generated by default as identity primary key,
    filter_type text not null,
    filter_value text not null,
    sort_order integer not null default 0,
    source_hash text not null,
    refreshed_at timestamptz not null default now(),
    unique (filter_type, filter_value)
);

create table if not exists public.app_delta_run (
    id uuid primary key default gen_random_uuid(),
    mode text not null default 'upgrade',
    status text not null default 'running',
    scope text not null default 'annonces_current',
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    dossiers_detected integer not null default 0,
    dossiers_upserted integer not null default 0,
    details_upserted integer not null default 0,
    work_items_replaced integer not null default 0,
    filters_replaced integer not null default 0,
    deleted_dossiers integer not null default 0,
    notes jsonb not null default '{}'::jsonb
);

create table if not exists public.app_mandat_current (
    app_dossier_id bigint primary key,
    hektor_annonce_id bigint not null,
    archive text,
    diffusable text,
    nb_portails_actifs integer not null default 0,
    has_diffusion_error boolean not null default false,
    portails_resume text,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    ville text,
    type_bien text,
    prix numeric,
    commercial_id text,
    commercial_nom text,
    agence_nom text,
    statut_annonce text,
    priority text,
    offre_id text,
    compromis_id text,
    vente_id text,
    source_updated_at timestamptz,
    refreshed_at timestamptz not null default now()
);

create table if not exists public.app_mandat_register_current (
    register_row_id text primary key,
    app_dossier_id bigint,
    hektor_annonce_id bigint not null,
    photo_url_listing text,
    images_preview_json text,
    adresse_privee_listing text,
    adresse_detail text,
    code_postal text,
    code_postal_prive_detail text,
    ville_privee_detail text,
    archive text,
    diffusable text,
    nb_portails_actifs integer not null default 0,
    has_diffusion_error boolean not null default false,
    portails_resume text,
    numero_dossier text,
    numero_mandat text,
    register_sort_group integer not null default 1,
    register_sort_num bigint not null default 0,
    titre_bien text,
    ville text,
    type_bien text,
    prix numeric,
    commercial_id text,
    commercial_nom text,
    negociateur_email text,
    agence_nom text,
    statut_annonce text,
    validation_diffusion_state text,
    mandat_source_id text,
    mandat_numero_reference text,
    mandat_type text,
    mandat_type_source text,
    mandat_date_debut text,
    mandat_date_fin text,
    mandat_montant numeric,
    mandants_texte text,
    mandat_note text,
    priority text,
    offre_id text,
    offre_state text,
    offre_last_proposition_type text,
    compromis_id text,
    compromis_state text,
    vente_id text,
    source_updated_at timestamptz,
    register_source_kind text,
    register_detail_available boolean not null default false,
    register_version_count integer not null default 1,
    register_embedded_avenant_count integer not null default 0,
    register_history_json text,
    register_avenants_json text,
    register_detail_payload_json text,
    source_hash text not null,
    refreshed_at timestamptz not null default now()
);

create table if not exists public.app_mandat_broadcast_current (
    app_dossier_id bigint not null,
    hektor_annonce_id bigint not null,
    passerelle_key text not null,
    commercial_key text not null default '',
    commercial_id text,
    commercial_nom text,
    commercial_prenom text,
    current_state text,
    export_status text,
    is_success boolean not null default false,
    is_error boolean not null default false,
    refreshed_at timestamptz not null default now(),
    primary key (app_dossier_id, passerelle_key, commercial_key)
);

create table if not exists public.app_diffusion_request (
    id uuid primary key default gen_random_uuid(),
    app_dossier_id bigint not null,
    hektor_annonce_id bigint not null,
    numero_dossier text,
    numero_mandat text,
    titre_bien text not null,
    commercial_nom text,
    request_type text not null default 'demande_diffusion',
    requested_by uuid not null references auth.users(id) on delete cascade,
    requested_by_label text,
    requested_at timestamptz not null default now(),
    request_status text not null default 'pending',
    request_comment text,
    request_reason text,
    admin_response text,
    refusal_reason text,
    follow_up_needed boolean not null default false,
    follow_up_at timestamptz,
    relaunch_count integer not null default 0,
    processed_by uuid references auth.users(id) on delete set null,
    processed_by_label text,
    processed_at timestamptz,
    processing_comment text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_app_mandat_current_commercial on public.app_mandat_current (commercial_id, commercial_nom);
create index if not exists idx_app_mandat_current_statut on public.app_mandat_current (statut_annonce, archive, diffusable);
create index if not exists idx_app_mandat_register_annonce on public.app_mandat_register_current (hektor_annonce_id, numero_mandat);
create index if not exists idx_app_mandat_register_dossier on public.app_mandat_register_current (app_dossier_id);
create index if not exists idx_app_mandat_register_statut on public.app_mandat_register_current (statut_annonce, register_source_kind);
create index if not exists idx_app_mandat_register_commercial on public.app_mandat_register_current (commercial_nom, negociateur_email);
create index if not exists idx_app_mandat_register_sort on public.app_mandat_register_current (register_sort_group asc, register_sort_num desc, hektor_annonce_id desc, register_row_id desc);
create index if not exists idx_app_mandat_broadcast_current_annonce on public.app_mandat_broadcast_current (hektor_annonce_id, passerelle_key);
create index if not exists idx_app_diffusion_request_status on public.app_diffusion_request (request_status, requested_at desc);
create index if not exists idx_app_diffusion_request_dossier on public.app_diffusion_request (app_dossier_id);

create index if not exists idx_app_dossier_v1_annonce on public.app_dossier_v1 (hektor_annonce_id);
create index if not exists idx_app_dossier_v1_statut on public.app_dossier_v1 (statut_annonce, validation_diffusion_state, etat_visibilite);
create index if not exists idx_app_dossier_v1_commercial on public.app_dossier_v1 (commercial_id, commercial_nom);
create index if not exists idx_app_dossier_v1_priority on public.app_dossier_v1 (priority, has_open_blocker);
create index if not exists idx_app_dossier_detail_v1_annonce on public.app_dossier_detail_v1 (hektor_annonce_id);
create index if not exists idx_app_work_item_v1_status on public.app_work_item_v1 (work_status, internal_status, priority);
create index if not exists idx_app_work_item_v1_annonce on public.app_work_item_v1 (hektor_annonce_id);
create index if not exists idx_app_filter_catalog_v1_type on public.app_filter_catalog_v1 (filter_type, sort_order, filter_value);
create index if not exists idx_app_dossier_current_annonce on public.app_dossier_current (hektor_annonce_id);
create index if not exists idx_app_dossier_current_statut on public.app_dossier_current (statut_annonce, archive, diffusable);
create index if not exists idx_app_dossier_current_commercial on public.app_dossier_current (commercial_id, commercial_nom);
create index if not exists idx_app_dossier_detail_current_annonce on public.app_dossier_detail_current (hektor_annonce_id);
create index if not exists idx_app_work_item_current_status on public.app_work_item_current (work_status, internal_status, priority);
create index if not exists idx_app_work_item_current_annonce on public.app_work_item_current (hektor_annonce_id);
create index if not exists idx_app_filter_catalog_current_type on public.app_filter_catalog_current_store (filter_type, sort_order, filter_value);
create index if not exists idx_app_delta_run_started_at on public.app_delta_run (started_at desc, status);

create or replace view public.app_latest_sync_run
with (security_invoker=on) as
select *
from public.app_sync_run
order by generated_at desc
limit 1;

create or replace view public.app_dossiers_current
with (security_invoker=on) as
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.archive,
    d.diffusable,
    d.adresse_privee_listing,
    d.adresse_detail,
    d.code_postal,
    d.code_postal_prive_detail,
    d.ville_privee_detail,
    d.nb_portails_actifs,
    d.has_diffusion_error,
    d.portails_resume,
    d.offre_id,
    d.offre_state,
    d.compromis_id,
    d.compromis_state,
    d.vente_id,
    d.numero_dossier,
    d.numero_mandat,
    d.titre_bien,
    d.ville,
    d.type_bien,
    d.prix,
    d.commercial_id,
    d.commercial_nom,
    d.negociateur_email,
    d.agence_nom,
    d.statut_annonce,
    d.photo_url_listing,
    d.images_preview_json,
    d.validation_diffusion_state,
    d.mandat_type,
    d.mandat_type_source,
    d.mandat_date_debut,
    d.mandat_date_fin,
    d.mandat_montant,
    d.mandants_texte,
    d.etat_visibilite,
    d.alerte_principale,
    d.priority,
    d.has_open_blocker,
    d.commentaire_resume,
    d.date_relance_prevue,
    d.dernier_event_type,
    d.dernier_work_status,
    d.offre_last_proposition_type
from public.app_dossier_current d
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.archive,
    d.diffusable,
    d.adresse_privee_listing,
    d.adresse_detail,
    d.code_postal,
    d.code_postal_prive_detail,
    d.ville_privee_detail,
    d.nb_portails_actifs,
    d.has_diffusion_error,
    d.portails_resume,
    d.offre_id,
    d.offre_state,
    d.compromis_id,
    d.compromis_state,
    d.vente_id,
    d.numero_dossier,
    d.numero_mandat,
    d.titre_bien,
    d.ville,
    d.type_bien,
    d.prix,
    d.commercial_id,
    d.commercial_nom,
    d.negociateur_email,
    d.agence_nom,
    d.statut_annonce,
    d.photo_url_listing,
    d.images_preview_json,
    d.validation_diffusion_state,
    d.mandat_type,
    d.mandat_type_source,
    d.mandat_date_debut,
    d.mandat_date_fin,
    d.mandat_montant,
    d.mandants_texte,
    d.etat_visibilite,
    d.alerte_principale,
    d.priority,
    d.has_open_blocker,
    d.commentaire_resume,
    d.date_relance_prevue,
    d.dernier_event_type,
    d.dernier_work_status,
    d.offre_last_proposition_type
from public.app_dossier_v1 d
join public.app_latest_sync_run r on r.id = d.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

create or replace view public.app_dossier_details_current
with (security_invoker=on) as
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.detail_payload_json
from public.app_dossier_detail_current d
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    d.app_dossier_id,
    d.hektor_annonce_id,
    d.detail_payload_json
from public.app_dossier_detail_v1 d
join public.app_latest_sync_run r on r.id = d.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

create or replace view public.app_work_items_current
with (security_invoker=on) as
select
    w.app_dossier_id,
    w.hektor_annonce_id,
    w.archive,
    w.numero_dossier,
    w.numero_mandat,
    w.titre_bien,
    w.commercial_nom,
    w.type_demande_label,
    w.work_status,
    w.internal_status,
    w.priority,
    w.validation_diffusion_state,
    w.etat_visibilite,
    w.motif_blocage,
    w.has_open_blocker,
    w.next_action,
    w.date_relance_prevue,
    w.date_entree_file,
    w.date_derniere_action,
    w.age_jours
from public.app_work_item_current w
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    w.app_dossier_id,
    w.hektor_annonce_id,
    w.archive,
    w.numero_dossier,
    w.numero_mandat,
    w.titre_bien,
    w.commercial_nom,
    w.type_demande_label,
    w.work_status,
    w.internal_status,
    w.priority,
    w.validation_diffusion_state,
    w.etat_visibilite,
    w.motif_blocage,
    w.has_open_blocker,
    w.next_action,
    w.date_relance_prevue,
    w.date_entree_file,
    w.date_derniere_action,
    w.age_jours
from public.app_work_item_v1 w
join public.app_latest_sync_run r on r.id = w.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

create or replace view public.app_filter_catalog_current
with (security_invoker=on) as
select
    c.filter_type,
    c.filter_value,
    c.sort_order
from public.app_filter_catalog_current_store c
where exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed')
union all
select
    c.filter_type,
    c.filter_value,
    c.sort_order
from public.app_filter_catalog_v1 c
join public.app_latest_sync_run r on r.id = c.sync_run_id
where not exists (select 1 from public.app_delta_run where scope = 'annonces_current' and status = 'completed');

create or replace view public.app_dashboard_v1
with (security_invoker=on) as
select
    null::uuid as sync_run_id,
    (select count(*) from public.app_dossiers_current) as total_dossiers,
    (select count(*) from public.app_work_items_current) as total_demandes,
    (select count(*) from public.app_dossiers_current where coalesce(numero_mandat, '') = '') as total_sans_mandat,
    (select count(*) from public.app_dossiers_current where coalesce(has_open_blocker, false) = true) as total_bloques,
    (select count(*) from public.app_dossiers_current where coalesce(validation_diffusion_state, '') = 'valide') as total_valides_diffusion,
    (select count(*) from public.app_dossiers_current where coalesce(etat_visibilite, '') = 'visible') as total_visibles;

create or replace view public.app_mandats_current
with (security_invoker=on) as
select *
from public.app_mandat_current;

create or replace view public.app_registre_mandats_current
with (security_invoker=on) as
select *
from public.app_mandat_register_current;

create or replace view public.app_mandat_broadcasts_current
with (security_invoker=on) as
select *
from public.app_mandat_broadcast_current;

create or replace view public.app_diffusion_requests_current
with (security_invoker=on) as
select
    r.*,
    coalesce(req.display_name, req.email, r.requested_by_label) as requested_by_name,
    coalesce(proc.display_name, proc.email, r.processed_by_label) as processed_by_name
from public.app_diffusion_request r
left join public.app_user_profile req on req.id = r.requested_by
left join public.app_user_profile proc on proc.id = r.processed_by;

create or replace function public.is_app_user_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.app_user_profile p
        where p.id = auth.uid()
          and p.is_active = true
    );
$$;

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.app_user_profile p
        where p.id = auth.uid()
          and p.role = 'admin'
          and p.is_active = true
    );
$$;

create or replace function public.is_app_manager_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.app_user_profile p
        where p.id = auth.uid()
          and p.role in ('admin', 'manager')
          and p.is_active = true
    );
$$;

alter table public.app_user_profile enable row level security;
alter table public.app_sync_run enable row level security;
alter table public.app_summary_snapshot enable row level security;
alter table public.app_dossier_v1 enable row level security;
alter table public.app_dossier_detail_v1 enable row level security;
alter table public.app_work_item_v1 enable row level security;
alter table public.app_filter_catalog_v1 enable row level security;
alter table public.app_dossier_current enable row level security;
alter table public.app_dossier_detail_current enable row level security;
alter table public.app_work_item_current enable row level security;
alter table public.app_filter_catalog_current_store enable row level security;
alter table public.app_delta_run enable row level security;
alter table public.app_mandat_current enable row level security;
alter table public.app_mandat_register_current enable row level security;
alter table public.app_mandat_broadcast_current enable row level security;
alter table public.app_diffusion_request enable row level security;

create policy "profiles_select_self_or_admin"
on public.app_user_profile
for select
using (
    id = auth.uid()
    or public.is_app_admin()
);

create policy "app_data_select_active_users"
on public.app_sync_run
for select
using (public.is_app_user_active());

create policy "app_summary_select_active_users"
on public.app_summary_snapshot
for select
using (public.is_app_user_active());

create policy "app_dossiers_select_active_users"
on public.app_dossier_v1
for select
using (public.is_app_user_active());

create policy "app_dossier_details_select_active_users"
on public.app_dossier_detail_v1
for select
using (public.is_app_user_active());

create policy "app_work_items_select_active_users"
on public.app_work_item_v1
for select
using (public.is_app_user_active());

create policy "app_filter_catalog_select_active_users"
on public.app_filter_catalog_v1
for select
using (public.is_app_user_active());

create policy "app_dossier_current_select_active_users"
on public.app_dossier_current
for select
using (public.is_app_user_active());

create policy "app_dossier_detail_current_select_active_users"
on public.app_dossier_detail_current
for select
using (public.is_app_user_active());

create policy "app_work_item_current_select_active_users"
on public.app_work_item_current
for select
using (public.is_app_user_active());

create policy "app_filter_catalog_current_store_select_active_users"
on public.app_filter_catalog_current_store
for select
using (public.is_app_user_active());

create policy "app_delta_run_select_admin"
on public.app_delta_run
for select
using (public.is_app_manager_or_admin());


create policy "app_mandat_current_select_active_users"
on public.app_mandat_current
for select
using (public.is_app_user_active());

create policy "app_mandat_register_current_select_active_users"
on public.app_mandat_register_current
for select
using (public.is_app_user_active());

create policy "app_mandat_broadcast_current_select_active_users"
on public.app_mandat_broadcast_current
for select
using (public.is_app_user_active());

create policy "app_diffusion_request_select_active_users"
on public.app_diffusion_request
for select
using (public.is_app_user_active());

create policy "app_diffusion_request_insert_active_users"
on public.app_diffusion_request
for insert
with check (
    public.is_app_user_active()
    and requested_by = auth.uid()
);

create policy "app_diffusion_request_update_admin"
on public.app_diffusion_request
for update
using (public.is_app_manager_or_admin())
with check (public.is_app_manager_or_admin());

create policy "profiles_update_self"
on public.app_user_profile
for update
using (id = auth.uid())
with check (id = auth.uid());
