import type { DashboardSummary, DiffusionRequest, DiffusionRequestEvent, DiffusionTarget, Dossier, MandatBroadcast, MandatRecord, UserProfile, WorkItem } from '../types'

export const mockSummary: DashboardSummary = {
  total_dossiers: 55976,
  total_demandes: 21377,
  total_sans_mandat: 31683,
  total_bloques: 0,
  total_valides_diffusion: 1310,
  total_visibles: 406,
}

export const mockDossiers: Dossier[] = [
  {
    app_dossier_id: 32621,
    hektor_annonce_id: 4,
    photo_url_listing: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=240&q=60',
    numero_dossier: 'VA1926',
    numero_mandat: '17125',
    titre_bien: 'Grand T3 secteur Bellevue avec Garage',
    ville: 'Saint-Etienne',
    type_bien: '2',
    prix: 78000,
    commercial_id: '5',
    commercial_nom: 'Melanie LEGRAND',
    negociateur_email: 'melanie.legrand@gti.test',
    statut_annonce: 'Vendu',
    validation_diffusion_state: 'valide',
    etat_visibilite: 'diffusable_non_visible',
    alerte_principale: null,
    priority: 'high',
    has_open_blocker: false,
    commentaire_resume: '',
    date_relance_prevue: null,
    dernier_event_type: 'diffusable_non_visible',
    dernier_work_status: 'pending',
  },
  {
    app_dossier_id: 5502,
    hektor_annonce_id: 15,
    numero_dossier: 'VA1988',
    numero_mandat: '16635',
    titre_bien: 'T3 loue, ravalement facade vote',
    ville: 'Saint-Etienne',
    type_bien: '2',
    prix: 69000,
    commercial_id: '5',
    commercial_nom: 'Melanie LEGRAND',
    negociateur_email: 'melanie.legrand@gti.test',
    statut_annonce: 'Vendu',
    validation_diffusion_state: 'valide',
    etat_visibilite: 'diffusable_non_visible',
    alerte_principale: null,
    priority: 'high',
    has_open_blocker: false,
    commentaire_resume: '',
    date_relance_prevue: null,
    dernier_event_type: 'diffusable_non_visible',
    dernier_work_status: 'pending',
  },
]

export const mockWorkItems: WorkItem[] = [
  {
    app_dossier_id: 1,
    hektor_annonce_id: 44506,
    photo_url_listing: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=240&q=60',
    numero_dossier: 'VM18892',
    numero_mandat: '12960',
    titre_bien: 'Appartement T4 avec jardin',
    commercial_nom: 'Melanie LEGRAND',
    negociateur_email: 'melanie.legrand@gti.test',
    agence_nom: 'GTI Saint-Etienne',
    type_demande_label: 'Mandat actif non diffusable',
    work_status: 'pending',
    internal_status: 'a_controler',
    priority: 'high',
    validation_diffusion_state: 'a_controler',
    etat_visibilite: 'non_diffusable',
    motif_blocage: null,
    has_open_blocker: false,
    next_action: null,
    date_relance_prevue: null,
    date_entree_file: '2026-03-24T09:00:00Z',
    date_derniere_action: '2026-03-24T09:00:00Z',
    age_jours: 0,
  },
]

export const mockUserProfile: UserProfile = {
  id: 'local-user',
  email: 'local@gti.test',
  role: 'admin',
  first_name: 'Mode',
  last_name: 'local',
  display_name: 'Mode local',
  is_active: true,
}

export const mockMandats: MandatRecord[] = [
  {
    app_dossier_id: 32621,
    hektor_annonce_id: 4,
    photo_url_listing: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=240&q=60',
    archive: '0',
    diffusable: '1',
    nb_portails_actifs: 2,
    has_diffusion_error: false,
    portails_resume: 'bienicidirect, leboncoinDirect',
    numero_dossier: 'VA1926',
    numero_mandat: '17125',
    titre_bien: 'Grand T3 secteur Bellevue avec Garage',
    ville: 'Saint-Etienne',
    type_bien: 'Appartement',
    prix: 78000,
    commercial_id: '5',
    commercial_nom: 'Melanie LEGRAND',
    negociateur_email: 'melanie.legrand@gti.test',
    agence_nom: 'GTI Saint-Etienne',
    statut_annonce: 'Actif',
    priority: 'high',
    offre_id: null,
    compromis_id: null,
    vente_id: null,
    source_updated_at: '2026-03-26T10:30:00Z',
    refreshed_at: '2026-03-27T08:30:00Z',
  },
]

export const mockMandatBroadcasts: MandatBroadcast[] = [
  {
    app_dossier_id: 32621,
    hektor_annonce_id: 4,
    passerelle_key: 'leboncoinDirect',
    commercial_key: '5',
    commercial_id: '5',
    commercial_nom: 'Melanie LEGRAND',
    commercial_prenom: '',
    current_state: 'broadcasted',
    export_status: 'exported',
    is_success: true,
    is_error: false,
    refreshed_at: '2026-03-27T08:30:00Z',
  },
  {
    app_dossier_id: 32621,
    hektor_annonce_id: 4,
    passerelle_key: 'bienicidirect',
    commercial_key: '5',
    commercial_id: '5',
    commercial_nom: 'Melanie LEGRAND',
    commercial_prenom: '',
    current_state: 'broadcasted',
    export_status: 'exported',
    is_success: true,
    is_error: false,
    refreshed_at: '2026-03-27T08:30:00Z',
  },
]

export const mockDiffusionRequests: DiffusionRequest[] = [
  {
    id: 'req-1',
    app_dossier_id: 32621,
    hektor_annonce_id: 4,
    numero_dossier: 'VA1926',
    numero_mandat: '17125',
    titre_bien: 'Grand T3 secteur Bellevue avec Garage',
    commercial_nom: 'Melanie LEGRAND',
    request_type: 'demande_diffusion',
    requested_by: 'local-user',
    requested_by_label: 'Mode local',
    requested_by_name: 'Mode local',
    requested_at: '2026-03-27T08:45:00Z',
    request_status: 'pending',
    request_comment: 'Merci de verifier la diffusion multi-portails.',
    request_reason: 'Merci de verifier la diffusion multi-portails.',
    admin_response: null,
    refusal_reason: null,
    follow_up_needed: false,
    follow_up_at: null,
    relaunch_count: 0,
    processed_by: null,
    processed_by_label: null,
    processed_by_name: null,
    processed_at: null,
    processing_comment: null,
  },
]

export const mockDiffusionRequestEvents: DiffusionRequestEvent[] = [
  {
    id: 'event-1',
    diffusion_request_id: 'req-1',
    event_type: 'request_created',
    event_label: 'Demande envoyee',
    event_at: '2026-03-27T08:45:00Z',
    actor_user_id: 'local-user',
    actor_name: 'Mode local',
    actor_role: 'nego',
    payload_json: JSON.stringify({ message: 'Merci de verifier la diffusion multi-portails.' }),
    created_at: '2026-03-27T08:45:00Z',
  },
]

export const mockDiffusionTargets: DiffusionTarget[] = [
  {
    app_dossier_id: 32621,
    hektor_annonce_id: 4,
    hektor_broadcast_id: '2',
    portal_key: 'bienicidirect',
    target_state: 'enabled',
    source_ref: 'mock_seed',
    note: 'Cible locale de demonstration',
    requested_by_role: 'admin',
    requested_by_name: 'Mode local',
    requested_at: '2026-03-31T10:00:00Z',
    last_applied_at: null,
    last_apply_status: null,
    last_apply_error: null,
  },
  {
    app_dossier_id: 32621,
    hektor_annonce_id: 4,
    hektor_broadcast_id: '5',
    portal_key: 'leboncoinDirect',
    target_state: 'enabled',
    source_ref: 'mock_seed',
    note: 'Cible locale de demonstration',
    requested_by_role: 'admin',
    requested_by_name: 'Mode local',
    requested_at: '2026-03-31T10:00:00Z',
    last_applied_at: null,
    last_apply_status: null,
    last_apply_error: null,
  },
]
